### ISSUE TITLE
青羽 美咲 not exist

### ISSUE THREAD

**Issue by niceb5y** [ynifamily3/miel#1]
なんとぉー!
![青羽 美咲](https://user-images.githubusercontent.com/1621389/67658345-ac279380-f99c-11e9-9297-c0f5d7b51018.png)

**Comment by niceb5y** [comment]
![青羽 美咲](https://user-images.githubusercontent.com/1621389/67658345-ac279380-f99c-11e9-9297-c0f5d7b51018.png)

**Comment by ynifamily3** [comment]
https://miel.dev/proj/million_live_type_wallpaper/index.html
